### ISSUE TITLE
能否保留或者兼容mysql

### ISSUE THREAD

**Issue by Teddy-Zhu** [yiiu-co/yiiu#4]
看到删除了 初始化的sql ,想问下能不能兼容一下, 毕竟mysql还是比sqlite稳,大部分人还是用mysql的

**Comment by tomoya92** [comment]
@Teddy-Zhu 代码没动什么，删了的是初始化权限的脚本，初始化权限已经用程序实现了，启动后表自动创建，数据自动初始化好

关于使用mysql，在readme里有写到怎么切换

**Comment by Teddy-Zhu** [comment]
thx
