### ISSUE TITLE
未登录拦截

### ISSUE THREAD

**Issue by Teddy-Zhu** [yiiu-co/yiiu#6]
目前未登录直接访问登录用户界面会报错
```log
org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval
```

不知道是我配置问题还是其他什么问题

**Comment by tomoya92** [comment]
这个问题怎么重现的？我没登录，点其它用户名字，可以打开其它用户界面的呀

**Comment by Teddy-Zhu** [comment]
我没有配置github oauth , 未登录状态访问 https://xxx.xxx/user/profile 就会跳转 xxx.xxx/github_login
然后报错
![image](https://user-images.githubusercontent.com/9956097/32705256-fc6322f2-c84c-11e7-8f06-e7fb63d4dc33.png)

**Comment by tomoya92** [comment]
这是个问题，默认应该跳转到/login链接才对

**Comment by tomoya92** [comment]
没有找到解决办法，yiiu3.0版本里完全去掉了spring-security，这个问题也就不存在了，在此关闭，有解决办法再回来补上
