### ISSUE TITLE
选择不了节点

### ISSUE THREAD

**Issue by abowu** [yiiu-co/yiiu#7]
![qq 20171129114448](https://user-images.githubusercontent.com/6102417/33357013-cfcbb8ac-d4fa-11e7-868d-a30ae6b25f95.png)

**Comment by abowu** [comment]
原来是必须有二级节点
好像不太合理呢，我只需要几个一级就可以了

**Comment by tomoya92** [comment]
@abowu 现在做的就是二级的实现，而且维护一定时间的时候，节点也会增加的，所以二级的比较通用
